# Generated by Django 4.1.1 on 2023-06-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0011_alter_posts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-upload_date']},
        ),
    ]
