# Generated by Django 4.1.1 on 2023-06-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0003_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='liked_by',
        ),
    ]
