# Generated by Django 4.1.1 on 2023-06-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0004_remove_notification_commented_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
