# Generated by Django 4.1.1 on 2023-06-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0010_alter_comment_options_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-update_date']},
        ),
    ]
