# Generated by Django 4.2 on 2023-07-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='present_address',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
