# Generated by Django 4.2 on 2023-06-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Message', '0003_delete_inbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
