# Generated by Django 4.2 on 2023-06-25 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_Message', '0005_message_is_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sending_time', '-receiving_time']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='sending_time',
        ),
        migrations.AddField(
            model_name='message',
            name='receiving_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
