# Generated by Django 4.2 on 2023-06-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Message', '0006_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sending_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiving_time',
        ),
    ]
