# Generated by Django 4.1.1 on 2023-06-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Message', '0002_inbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
