# Generated by Django 4.2 on 2023-07-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0008_alter_userprofile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
